### ISSUE TITLE
Encountered Error In PHP implementation.

### ISSUE THREAD

**Issue by prosperoking** [prosperoking/kudaopenapi#2]
Encountered Error In PHP implementation.

Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /opt/lampp/htdocs/kudatest/vendor/prosperoking/kudaopenapi/src/KudaOpenApi.php on line 11

_Originally posted by @9jadev in https://github.com/prosperoking/kudaopenapi/issues/1#issuecomment-830775501_

**Comment by prosperoking** [comment]
This is because this library was developed with PHP 7.4 in mind.

**Comment by 9jadev** [comment]
The implementation is still on PHP 7.4

**Comment by prosperoking** [comment]
Please confirm you are running on php 7.4

**Comment by 9jadev** [comment]
php -v on shell 7.4.3

**Comment by prosperoking** [comment]
### Please, can I get more information about your development environment?
- Are you running your PHP code from the console or web browser? 
- Do you have multiple PHP versions installed?
- Can I have your ```phpinfo();``` screenshot

**Comment by 9jadev** [comment]
I have a screenshot [image](https://drive.google.com/file/d/1EOALxMo5owqH5PwxpXyAZ0NQcXHBrvCZ/view?usp=sharing) please click the image to find screenshot.

**Comment by prosperoking** [comment]
As you can see it's php 7.2.34. So, you definitely have multiple PHP versions on your machine.

**Comment by 9jadev** [comment]
so what can be done

**Comment by prosperoking** [comment]
you installed lampp based on what I can see from the path. You will have to find how to upgrade it or how to switch to the php version you installed without lampp
